### ISSUE TITLE
高版本spring解决方式

### ISSUE THREAD

**Issue by 31415926535x** [xichengxml/springboot-vue-template#26]
对于高版本的springboot-web，因为其不再支持原来的配置串，所以可以尝试如下的配置来达到同样的效果：

```yml
  web:
    resources:
      static-locations: classpath:/, classpath:/templates
```
